title: Parker Barrett
email: parkerbarrett1302@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Estimation and Tracking Software Engineer with a passion for navigation and robotics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://parkerbarrett959.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-architect

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
