remote_theme: "mmistakes/minimal-mistakes@latest"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-assets
url: "https://parkerbarrett959.github.io"
baseurl: ""
title: "Parker Barrett"
description: "Estimation and Tracking Software Engineer with a passion for GNSS-denied navigation and robotics."
author:
  name: "Parker Barrett"
  email: "parkerbarrett1302@gmail.com"
  url: "https://github.com/ParkerBarrett959"
  avatar: "/assets/images/avatar.jpg"
social_links:
  - { platform: "github", user_url: "https://github.com/ParkerBarrett959" }
  - { platform: "linkedin", user_url: "https://www.linkedin.com/in/parker-barrett-28360a161" }
  - { platform: "email", user_url: "mailto:parkerbarrett1302@gmail.com" }
paginate: 5
paginate_path: "/page:num/"
