title: Parker Barrett
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Developer Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://parkerbarrett959.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-architect

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
